name: Deploy to Hostinger FTP

on:
  push:
    branches:
      - main   # or master

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync files to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/dine_master/   # change to your directory
          local-dir: ./   # upload everything from repo root
          exclude: |
            **/.git/**
            **/.git*
            **/.github/**

      - name: Send Discord notification (success)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"✅ Deployment to Hostinger completed successfully!\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send Discord notification (failure)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"❌ Deployment to Hostinger FAILED! Check GitHub Actions logs.\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
